### ISSUE TITLE
Add another key-binding to execute commands directly.

### ISSUE THREAD

**Issue by LinArcX** [sudormrfbin/cheatsheet.nvim#11]
Hi. I'm using `cheatsheet.nvim` and mostly use it to call/run my custom commands and functions.

The only annoying issue is that it always filled in the command line if the selection row is a command.

I think you designed it in this way to let users edit the commands before run it? But me personally (for 90% of time) don't need to edit commands and just need to run them immediately.

In my opinion, we can add another keybinding like `<Ctrl-r>` (or whatever you prefer) for filling the command line and keep the `<ENTER>` to execute commands directly.

**Comment by sudormrfbin** [comment]
Hi @LinArcX ! Thanks for the PR, but I added a more configurable way of changing the keybinds in 9716f9a which also adds `Alt-Enter` as a default keybind for directly executing commands. Rebinding is also possible, so if you want to use `Enter` to directly execute and `Alt-Enter` to fill the command line:

```lua
require('cheatsheet').setup({
    telescope_mappings = {
        ['<CR>'] = require('cheatsheet.telescope.actions').select_or_execute,
        ['<A-CR>'] = require('cheatsheet.telescope.actions').select_or_fill_commandline,
    }
})

```
