### ISSUE TITLE
Disabling nerd-fonts cheatsheet does not work

### ISSUE THREAD

**Issue by mattrobineau** [sudormrfbin/cheatsheet.nvim#16]
I am using the following setup:

```
require("cheatsheet").setup({
    bundled_cheetsheets = {
        enabled = { "default", "regex", "netrw" },
        disabled = { "nerd-fonts" } -- also tried "nerdfonts"
    },
})
```

However, I still see nerd-fonts being added to the list:
![nerd fonts in list screenshot](https://user-images.githubusercontent.com/427379/151734123-f4ff621a-b9c9-40ad-88b4-372788c1fa8a.png)

**Comment by guivazcabral** [comment]
works for me

**Comment by mattrobineau** [comment]
I stopped using this plugin. Closing issue.

**Comment by greggannicott** [comment]
FWIW I've got the same issue.
