### ISSUE TITLE
How to make Cheatsheet.txt dynamic?

### ISSUE THREAD

**Issue by siduck76** [sudormrfbin/cheatsheet.nvim#7]
hi @sudormrfbin , very cool plugin! Im liking it so far but one thing bugs me . We can write our mappings in cheatsheet.txt , Is there anyway to make this automatic?

Im trying to add this plugin in NvChad and the user config contains this 

![image](https://user-images.githubusercontent.com/59060246/129481183-07a17445-900f-43b4-ab78-e231b928b199.png)

So obviously I cant define any mappings in the cheatsheet.txt since the user would change his mappings here and would have to manually do it again in cheatsheet.txt :c .

Is there a way get all defined mappings ( keys and their cmds) and get it work with cheatsheet.nvim?

**Comment by siduck76** [comment]
Ok so I think we could do this ourselves without using any plugin!

**Comment by siduck76** [comment]
So the main concept is to loop through the mapping table in chadrc , this way it is dynamic too + no need to define mappings in some file.

**Comment by siduck76** [comment]
# Concept 

Suppose the truzen table is gonna get printed 

![image](https://user-images.githubusercontent.com/59060246/129482252-11fa5354-990b-4aab-83a5-56f71ff6b388.png)

So the process could be like this : 

![image](https://user-images.githubusercontent.com/59060246/129482265-9f40bfb3-0e48-4c84-8f47-e84d4e1a96b1.png)

**Comment by sudormrfbin** [comment]
Hi @siduck76  :)

Glad to hear that you're trying to add it to NvChad! There was a [recent question](https://github.com/sudormrfbin/cheatsheet.nvim/issues/4#issuecomment-897085522) regarding the same issue, and I'm planning to solve it along with `whichkey.nvim` integration. I'm thinking of adding something like this...

```lua
local cheatsheet = require('cheatsheet.nvim')
cheatsheet.add_cheat("Toggle NvimTree", "<C-N>", "optional-section-name")
```

... so that it's possible to add them programmatically. Then I think it'll be easy for you to loop over the `mappings` table and add the cheats. Does that solve your usecase ?

**Comment by siduck76** [comment]
> Hi @siduck76 :)
> 
> Glad to hear that you're trying to add it to NvChad! There was a [recent question](https://github.com/sudormrfbin/cheatsheet.nvim/issues/4#issuecomment-897085522) regarding the same issue, and I'm planning to solve it along with `whichkey.nvim` integration. I'm thinking of adding something like this...
> 
> ```lua
> local cheatsheet = require('cheatsheet.nvim')
> cheatsheet.add_cheat("Toggle NvimTree", "<C-N>", "optional-section-name")
> ```
> 
> ... so that it's possible to add them programmatically. Then I think it'll be easy for you to loop over the `mappings` table and add the cheats. Does that solve your usecase ?

yes :D

**Comment by siduck76** [comment]
@sudormrfbin let me if this gets before 18th please! I need to release v1.0 before 19th of this month :c

**Comment by siduck76** [comment]
Also would it be possible to add heading for the mappings?

like : 

Telescope 

old files : <leader> fw 
buffer : <leader> fb

**Comment by siduck76** [comment]
> hi @sudormrfbin , very cool plugin! Im liking it so far but one thing bugs me . We can write our mappings in cheatsheet.txt , Is there anyway to make this automatic?
> 
> Im trying to add this plugin in NvChad and the user config contains this
> 
> ![image](https://user-images.githubusercontent.com/59060246/129481183-07a17445-900f-43b4-ab78-e231b928b199.png)
> 
> So obviously I cant define any mappings in the cheatsheet.txt since the user would change his mappings here and would have to manually do it again in cheatsheet.txt :c .
> 
> Is there a way get all defined mappings ( keys and their cmds) and get it work with cheatsheet.nvim?

So I have this mappings table , with multiple tables in it ( for each plugin ) so I wanna loop through and do something like this : 

```
local cheatsheet = require('cheatsheet.nvim')

for index, data in pairs(mappings) do
    print(index .. "\n")  

    for key, val in pairs(data) do
      cheatsheet.add_cheat(key, val)
    end
end
```

**Comment by sudormrfbin** [comment]
> @sudormrfbin let me if this gets before 18th please! I need to release v1.0 before 19th of this month :c

I'll try to finish it up before 18th then, most probably tomorrow :)

> Also would it be possible to add heading for the mappings?

That should be handled by sections:

```lua
add_cheat("old files", "<leader>fw", "Telescope")l
```

**Comment by siduck76** [comment]
> ```lua
> ```lua
> add_cheat("old files", "<leader>fw", "Telescope")
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
>       
> ```

is this a config? I didnt find it in the readme

**Comment by sudormrfbin** [comment]
I meant the `section-name` in the [readme](https://github.com/sudormrfbin/cheatsheet.nvim#cheatsheettxt-file-format)

> - `##` starts a metadata comment for specifying sections and tags.
>
>    `## section-name @tag1 @tag2`: here `section-name` is the name of a plugin or a simple name to group some cheats together. `tag1` and `tag2` are alternative names that you might later remember the section name with. For example the section name can be [`sandwich`](https://github.com/machakann/vim-sandwich) and the tag can be `@surround`.

**Comment by siduck76** [comment]
> I meant the `section-name` in the [readme](https://github.com/sudormrfbin/cheatsheet.nvim#cheatsheettxt-file-format)
> 
> > * `##` starts a metadata comment for specifying sections and tags.
> >   `## section-name @tag1 @tag2`: here `section-name` is the name of a plugin or a simple name to group some cheats together. `tag1` and `tag2` are alternative names that you might later remember the section name with. For example the section name can be [`sandwich`](https://github.com/machakann/vim-sandwich) and the tag can be `@surround`.

I cant write the cheatsheet keybinds manually tho :/ , isnt there any automatic way?

**Comment by siduck76** [comment]
Since the mappings file in NvChad config will be modified by the user , writing the cheatsheet manually which will get old ( when the user changes his mappings ) is not gonna work.

**Comment by sudormrfbin** [comment]
Oh you misunderstood me, `add_cheat("old files", "<leader>fw", "Telescope")` is the _proposed_ API I'm working on right now; it should be ready by today. I thought you didn't realize that it's possible to set sections already from the files, so I was suggesting that it'll also be possible programmatically after I push the new API.

**Comment by siduck76** [comment]
> Oh you misunderstood me, `add_cheat("old files", "<leader>fw", "Telescope")` is the _proposed_ API I'm working on right now; it should be ready by today. I thought you didn't realize that it's possible to set sections already from the files, so I was suggesting that it'll also be possible programmatically after I push the new API.

ohh cool , lemme know when it gets done :heart:

**Comment by sudormrfbin** [comment]
I've added `add_cheat` in 5be58ae:

```lua
local cheatsheet = require('cheatsheet')

for section, data in pairs(mappings) do
    for description, keymap in pairs(data) do
      cheatsheet.add_cheat(description, keymap, section)
    end
end
```

I suggest adding better worded descriptions for each of the mappings since here we are simply using the key name of the mapping in the table as a substitute (it doesn't play nice with the search because of underscores and camelCase).

**Comment by siduck76** [comment]
> I meant the `section-name` in the [readme](https://github.com/sudormrfbin/cheatsheet.nvim#cheatsheettxt-file-format)
> 
> > * `##` starts a metadata comment for specifying sections and tags.
> >   `## section-name @tag1 @tag2`: here `section-name` is the name of a plugin or a simple name to group some cheats together. `tag1` and `tag2` are alternative names that you might later remember the section name with. For example the section name can be [`sandwich`](https://github.com/machakann/vim-sandwich) and the tag can be `@surround`.

Thanks this works! Btw how do I make the cheatsheet popup ( telescope ) show and list out only cheatsheet made by mappings? I dont wanna list cheatsheet for default vim mappings . 

so I'll make two mappings : 

1. for :Cheatsheet ( will show default cheetsheet with default vim mappings and stuff )

2. for user cheatsheet  ( will show those from mappings table only )

**Comment by sudormrfbin** [comment]
You can do it like so (with cf069d8):

```lua
cheatsheet = require('cheatsheet')

-- for :Cheatsheet ( will show default cheetsheet with default vim mappings and stuff )
cheatsheet.show_cheatsheet_telescope()

-- for user cheatsheet ( will show those from mappings table only )
cheatsheet.show_cheatsheet_telescope({bundled_cheatsheets=false, bundled_plugin_cheatsheets=false})
```

**Comment by siduck76** [comment]
works perfect! 

![image](https://user-images.githubusercontent.com/59060246/129585761-f952ea65-2f1b-4633-956a-267a90abc1cd.png)
