### ISSUE TITLE
E5108: Error executing lua ...attempt to compare number with nil

### ISSUE THREAD

**Issue by timoleistner** [sudormrfbin/cheatsheet.nvim#9]
I have installed the plugin with
```
    use {
        'sudormrfbin/cheatsheet.nvim',

        requires = {
            {'nvim-telescope/telescope.nvim'},
            {'nvim-lua/popup.nvim'},
            {'nvim-lua/plenary.nvim'},
        }
    }
```
When running `:Cheatsheet` or pressing `<leader>?` I get:
```
Error detected while processing function <SNR>50_Cheatsheet:
line    5:
E5108: Error executing lua ...acker/start/cheatsheet.nvim/lua/cheatsheet/telescope.lua:44: attempt to compare number with nil
```
If you need more info of my config let me know :)

**Comment by bkesby** [comment]
I get the same issue also but with `<SNR>60_Cheatsheet'

**Comment by sudormrfbin** [comment]
It seems telescope [changed how the width of the window can be retrieved](https://github.com/nvim-telescope/telescope.nvim/pull/1039/files#diff-4936325bfc521d7cffc09fe0156becd4a4ba2ed169431c94bd63669fe0cc1a2aL79-R82) and cheatsheet uses this calculate the width of individual columns (section name, description and cheat). I pushed 3f0b718 as a fix, let me know if the issue persists :)

**Comment by timoleistner** [comment]
Its working now! Thanks for the quick fix :slightly_smiling_face:

**Comment by sudormrfbin** [comment]
@adrianlzt I can't reproduce it, is telescope up to date on your machine ?
